import type {
  Book,
  LibraryEntry,
  ReadingSession,
  Chapter,
  Note,
  Shelf,
  Author,
  Tag,
  ReadingGoal,
  ReadingStats,
  BookStatus,
  BookFormat,
  NoteType
} from './types';
import { subDays, subMonths, startOfYear, endOfYear, format, addDays } from 'date-fns';

// Mock data generators
const now = new Date();
const thisYear = now.getFullYear();

export const mockBooks: Book[] = [
  {
    id: '1',
    title: 'Atomic Habits',
    subtitle: 'An Easy & Proven Way to Build Good Habits & Break Bad Ones',
    author: 'James Clear',
    authorId: 'author-1',
    coverUrl: 'https://covers.openlibrary.org/b/isbn/9780735211292-L.jpg',
    coverColor: '#b7791f',
    description: 'No matter your goals, Atomic Habits offers a proven framework for improving--every day. James Clear, one of the world\'s leading experts on habit formation, reveals practical strategies that will teach you exactly how to form good habits, break bad ones, and master the tiny behaviors that lead to remarkable results.',
    isbn: '0735211299',
    isbn13: '9780735211292',
    genres: ['Self-Improvement', 'Psychology', 'Productivity', 'Business'],
    format: 'paperback',
    pageCount: 320,
    publishedYear: 2018,
    publisher: 'Avery',
    language: 'en',
    openLibraryId: 'OL1234567W',
    createdAt: subDays(now, 180),
    updatedAt: subDays(now, 10),
  },
  {
    id: '2',
    title: 'Tomorrow, and Tomorrow, and Tomorrow',
    author: 'Gabrielle Zevin',
    authorId: 'author-2',
    coverUrl: 'https://covers.openlibrary.org/b/isbn/9780593321201-L.jpg',
    coverColor: '#64748b',
    description: 'A magnificent and moving novel about two friends--often in love, but never lovers--who come together as creative partners in the world of video game design.',
    isbn: '0593321200',
    isbn13: '9780593321201',
    genres: ['Fiction', 'Literary Fiction', 'Technology', 'Friendship'],
    format: 'hardcover',
    pageCount: 416,
    publishedYear: 2022,
    publisher: 'Knopf',
    language: 'en',
    openLibraryId: 'OL2345678W',
    createdAt: subDays(now, 120),
    updatedAt: subDays(now, 5),
  },
  {
    id: '3',
    title: 'The Creative Act: A Way of Being',
    author: 'Rick Rubin',
    authorId: 'author-3',
    coverUrl: 'https://covers.openlibrary.org/b/isbn/9780593652886-L.jpg',
    coverColor: '#c2410c',
    description: 'Many famed music producers are known for a particular sound. Rick Rubin is known for something else: for creating a space where artists can discover who they really are.',
    isbn: '0593652885',
    isbn13: '9780593652886',
    genres: ['Creativity', 'Non-Fiction', 'Art', 'Philosophy'],
    format: 'kindle',
    pageCount: 432,
    publishedYear: 2023,
    publisher: 'Penguin Press',
    language: 'en',
    openLibraryId: 'OL3456789W',
    createdAt: subDays(now, 90),
    updatedAt: subDays(now, 2),
  },
  {
    id: '4',
    title: 'The Midnight Library',
    author: 'Matt Haig',
    authorId: 'author-4',
    coverUrl: 'https://covers.openlibrary.org/b/isbn/9780525559474-L.jpg',
    coverColor: '#334155',
    description: 'Between life and death there is a library. When Nora Seed finds herself in the Midnight Library, she has a chance to make things right.',
    isbn: '0525559475',
    isbn13: '9780525559474',
    genres: ['Fiction', 'Fantasy', 'Philosophy', 'Mental Health'],
    format: 'paperback',
    pageCount: 304,
    publishedYear: 2020,
    publisher: 'Viking',
    language: 'en',
    openLibraryId: 'OL4567890W',
    createdAt: subDays(now, 60),
    updatedAt: subDays(now, 1),
  },
  {
    id: '5',
    title: 'Project Hail Mary',
    author: 'Andy Weir',
    authorId: 'author-5',
    coverUrl: 'https://covers.openlibrary.org/b/isbn/9780593135204-L.jpg',
    coverColor: '#15803d',
    description: 'Ryland Grace is the sole survivor on a desperate, last-chance mission--and if he fails, humanity and the earth itself will perish.',
    isbn: '0593135202',
    isbn13: '9780593135204',
    genres: ['Science Fiction', 'Space', 'Adventure', 'Humor'],
    format: 'audiobook',
    pageCount: 496,
    publishedYear: 2021,
    publisher: 'Ballantine Books',
    language: 'en',
    openLibraryId: 'OL5678901W',
    createdAt: subDays(now, 45),
    updatedAt: subDays(now, 3),
  },
  {
    id: '6',
    title: 'Braiding Sweetgrass',
    subtitle: 'Indigenous Wisdom, Scientific Knowledge and the Teachings of Plants',
    author: 'Robin Wall Kimmerer',
    authorId: 'author-6',
    coverUrl: 'https://covers.openlibrary.org/b/isbn/9781571313560-L.jpg',
    coverColor: '#7c3aed',
    description: 'Drawing on her life as an indigenous scientist, a mother, and a woman, Kimmerer shows how other living beings offer us gifts and lessons.',
    isbn: '1571313567',
    isbn13: '9781571313560',
    genres: ['Nature', 'Indigenous Wisdom', 'Science', 'Memoir'],
    format: 'hardcover',
    pageCount: 408,
    publishedYear: 2013,
    publisher: 'Milkweed Editions',
    language: 'en',
    openLibraryId: 'OL6789012W',
    createdAt: subDays(now, 30),
    updatedAt: subDays(now, 7),
  },
  {
    id: '7',
    title: 'The Psychology of Money',
    subtitle: 'Timeless Lessons on Wealth, Greed, and Happiness',
    author: 'Morgan Housel',
    authorId: 'author-7',
    coverUrl: 'https://covers.openlibrary.org/b/isbn/9780857197689-L.jpg',
    coverColor: '#be185d',
    description: 'Doing well with money isn\'t necessarily about what you know. It\'s about how you behave.',
    isbn: '0857197681',
    isbn13: '9780857197689',
    genres: ['Finance', 'Psychology', 'Self-Improvement', 'Economics'],
    format: 'paperback',
    pageCount: 256,
    publishedYear: 2020,
    publisher: 'Harriman House',
    language: 'en',
    openLibraryId: 'OL7890123W',
    createdAt: subDays(now, 20),
    updatedAt: subDays(now, 4),
  },
  {
    id: '8',
    title: 'Klara and the Sun',
    author: 'Kazuo Ishiguro',
    authorId: 'author-8',
    coverUrl: 'https://covers.openlibrary.org/b/isbn/9780593318171-L.jpg',
    coverColor: '#0891b2',
    description: 'From her place in the store, Klara, an Artificial Friend with outstanding observational qualities, watches carefully the behavior of those who come in to browse.',
    isbn: '059331817X',
    isbn13: '9780593318171',
    genres: ['Science Fiction', 'Literary Fiction', 'AI', 'Dystopian'],
    format: 'kindle',
    pageCount: 320,
    publishedYear: 2021,
    publisher: 'Knopf',
    language: 'en',
    openLibraryId: 'OL8901234W',
    createdAt: subDays(now, 15),
    updatedAt: subDays(now, 6),
  },
];

export const mockLibraryEntries: LibraryEntry[] = [
  {
    id: 'entry-1',
    bookId: '1',
    book: mockBooks[0],
    status: 'reading',
    owned: true,
    rating: 4.5,
    difficulty: 2,
    emotionalImpact: 4,
    wouldRecommend: true,
    rereadValue: 5,
    dateAdded: subDays(now, 180),
    dateStarted: subDays(now, 15),
    shelfIds: ['shelf-1', 'shelf-3'],
    currentPage: 218,
    progressPercent: 68,
    createdAt: subDays(now, 180),
    updatedAt: subDays(now, 1),
  },
  {
    id: 'entry-2',
    bookId: '2',
    book: mockBooks[1],
    status: 'read',
    owned: true,
    rating: 5,
    difficulty: 3,
    emotionalImpact: 5,
    wouldRecommend: true,
    rereadValue: 4,
    dateAdded: subDays(now, 120),
    dateStarted: subDays(now, 100),
    dateFinished: subDays(now, 85),
    shelfIds: ['shelf-1', 'shelf-2'],
    currentPage: 416,
    progressPercent: 100,
    createdAt: subDays(now, 120),
    updatedAt: subDays(now, 85),
  },
  {
    id: 'entry-3',
    bookId: '3',
    book: mockBooks[2],
    status: 'read',
    owned: true,
    rating: 4.5,
    difficulty: 2,
    emotionalImpact: 4,
    wouldRecommend: true,
    rereadValue: 5,
    dateAdded: subDays(now, 90),
    dateStarted: subDays(now, 80),
    dateFinished: subDays(now, 65),
    shelfIds: ['shelf-1', 'shelf-4'],
    currentPage: 432,
    progressPercent: 100,
    createdAt: subDays(now, 90),
    updatedAt: subDays(now, 65),
  },
  {
    id: 'entry-4',
    bookId: '4',
    book: mockBooks[3],
    status: 'read',
    owned: true,
    rating: 4,
    difficulty: 2,
    emotionalImpact: 5,
    wouldRecommend: true,
    rereadValue: 3,
    dateAdded: subDays(now, 60),
    dateStarted: subDays(now, 55),
    dateFinished: subDays(now, 45),
    shelfIds: ['shelf-1', 'shelf-2'],
    currentPage: 304,
    progressPercent: 100,
    createdAt: subDays(now, 60),
    updatedAt: subDays(now, 45),
  },
  {
    id: 'entry-5',
    bookId: '5',
    book: mockBooks[4],
    status: 'read',
    owned: true,
    rating: 5,
    difficulty: 3,
    emotionalImpact: 4,
    wouldRecommend: true,
    rereadValue: 4,
    dateAdded: subDays(now, 45),
    dateStarted: subDays(now, 40),
    dateFinished: subDays(now, 30),
    shelfIds: ['shelf-1', 'shelf-5'],
    currentPage: 496,
    progressPercent: 100,
    createdAt: subDays(now, 45),
    updatedAt: subDays(now, 30),
  },
  {
    id: 'entry-6',
    bookId: '6',
    book: mockBooks[5],
    status: 'tbr',
    owned: true,
    dateAdded: subDays(now, 30),
    shelfIds: ['shelf-1', 'shelf-6'],
    currentPage: 0,
    progressPercent: 0,
    createdAt: subDays(now, 30),
    updatedAt: subDays(now, 30),
  },
  {
    id: 'entry-7',
    bookId: '7',
    book: mockBooks[6],
    status: 'tbr',
    owned: false,
    dateAdded: subDays(now, 20),
    shelfIds: ['shelf-1'],
    currentPage: 0,
    progressPercent: 0,
    createdAt: subDays(now, 20),
    updatedAt: subDays(now, 20),
  },
  {
    id: 'entry-8',
    bookId: '8',
    book: mockBooks[7],
    status: 'tbr',
    owned: true,
    dateAdded: subDays(now, 15),
    shelfIds: ['shelf-1', 'shelf-2'],
    currentPage: 0,
    progressPercent: 0,
    createdAt: subDays(now, 15),
    updatedAt: subDays(now, 15),
  },
];

export const mockReadingSessions: ReadingSession[] = [
  {
    id: 'session-1',
    libraryEntryId: 'entry-1',
    startedAt: subDays(now, 1),
    endedAt: subDays(now, 1),
    pageStart: 200,
    pageEnd: 218,
    minutes: 45,
    mood: 'focused',
    notes: 'Great chapter on habit stacking. The 2-minute rule is brilliant.',
    createdAt: subDays(now, 1),
  },
  {
    id: 'session-2',
    libraryEntryId: 'entry-1',
    startedAt: subDays(now, 2),
    endedAt: subDays(now, 2),
    pageStart: 175,
    pageEnd: 200,
    minutes: 38,
    mood: 'engaged',
    notes: 'Identity-based habits vs outcome-based habits. This reframes everything.',
    createdAt: subDays(now, 2),
  },
  {
    id: 'session-3',
    libraryEntryId: 'entry-1',
    startedAt: subDays(now, 3),
    endedAt: subDays(now, 3),
    pageStart: 150,
    pageEnd: 175,
    minutes: 42,
    mood: 'focused',
    notes: 'The plateau of latent potential - so important to remember.',
    createdAt: subDays(now, 3),
  },
  {
    id: 'session-4',
    libraryEntryId: 'entry-1',
    startedAt: subDays(now, 4),
    endedAt: subDays(now, 4),
    pageStart: 125,
    pageEnd: 150,
    minutes: 35,
    mood: 'relaxed',
    notes: 'Environment design chapter. Making good habits obvious.',
    createdAt: subDays(now, 4),
  },
  {
    id: 'session-5',
    libraryEntryId: 'entry-1',
    startedAt: subDays(now, 5),
    endedAt: subDays(now, 5),
    pageStart: 100,
    pageEnd: 125,
    minutes: 40,
    mood: 'engaged',
    notes: 'The 4 laws of behavior change. Simple but powerful framework.',
    createdAt: subDays(now, 5),
  },
  {
    id: 'session-6',
    libraryEntryId: 'entry-2',
    startedAt: subDays(now, 100),
    endedAt: subDays(now, 100),
    pageStart: 0,
    pageEnd: 50,
    minutes: 60,
    mood: 'engaged',
    notes: 'Beautiful opening. The game design metaphor works perfectly.',
    createdAt: subDays(now, 100),
  },
  {
    id: 'session-7',
    libraryEntryId: 'entry-2',
    startedAt: subDays(now, 95),
    endedAt: subDays(now, 95),
    pageStart: 50,
    pageEnd: 120,
    minutes: 75,
    mood: 'emotional',
    notes: 'Sam and Sadie\'s friendship is so complex and real.',
    createdAt: subDays(now, 95),
  },
];

export const mockChapters: Chapter[] = [
  { id: 'ch-1', bookId: '1', number: 1, title: 'The Surprising Power of Atomic Habits', pageStart: 1, pageEnd: 12, percentComplete: 100, completed: true, createdAt: subDays(now, 15), updatedAt: subDays(now, 14) },
  { id: 'ch-2', bookId: '1', number: 2, title: 'How Your Habits Shape Your Identity', pageStart: 13, pageEnd: 28, percentComplete: 100, completed: true, createdAt: subDays(now, 14), updatedAt: subDays(now, 13) },
  { id: 'ch-3', bookId: '1', number: 3, title: 'How to Build Better Habits in 4 Simple Steps', pageStart: 29, pageEnd: 46, percentComplete: 100, completed: true, createdAt: subDays(now, 13), updatedAt: subDays(now, 12) },
  { id: 'ch-4', bookId: '1', number: 4, title: 'The Man Who Didn\'t Look Right', pageStart: 47, pageEnd: 62, percentComplete: 100, completed: true, createdAt: subDays(now, 12), updatedAt: subDays(now, 11) },
  { id: 'ch-5', bookId: '1', number: 5, title: 'The Best Way to Start a New Habit', pageStart: 63, pageEnd: 80, percentComplete: 100, completed: true, createdAt: subDays(now, 11), updatedAt: subDays(now, 10) },
  { id: 'ch-6', bookId: '1', number: 6, title: 'Motivation Is Overrated; Environment Often Matters More', pageStart: 81, pageEnd: 98, percentComplete: 100, completed: true, createdAt: subDays(now, 10), updatedAt: subDays(now, 9) },
  { id: 'ch-7', bookId: '1', number: 7, title: 'The Secret to Self-Control', pageStart: 99, pageEnd: 116, percentComplete: 100, completed: true, createdAt: subDays(now, 9), updatedAt: subDays(now, 8) },
  { id: 'ch-8', bookId: '1', number: 8, title: 'How to Make a Habit Irresistible', pageStart: 117, pageEnd: 134, percentComplete: 100, completed: true, createdAt: subDays(now, 8), updatedAt: subDays(now, 7) },
  { id: 'ch-9', bookId: '1', number: 9, title: 'The Role of Family and Friends in Shaping Your Habits', pageStart: 135, pageEnd: 152, percentComplete: 100, completed: true, createdAt: subDays(now, 7), updatedAt: subDays(now, 6) },
  { id: 'ch-10', bookId: '1', number: 10, title: 'How to Find and Fix the Causes of Your Bad Habits', pageStart: 153, pageEnd: 170, percentComplete: 100, completed: true, createdAt: subDays(now, 6), updatedAt: subDays(now, 5) },
  { id: 'ch-11', bookId: '1', number: 11, title: 'Walk Slowly, but Never Backward', pageStart: 171, pageEnd: 188, percentComplete: 100, completed: true, createdAt: subDays(now, 5), updatedAt: subDays(now, 4) },
  { id: 'ch-12', bookId: '1', number: 12, title: 'The Law of Least Effort', pageStart: 189, pageEnd: 206, percentComplete: 100, completed: true, createdAt: subDays(now, 4), updatedAt: subDays(now, 3) },
  { id: 'ch-13', bookId: '1', number: 13, title: 'How to Stop Procrastinating by Using the Two-Minute Rule', pageStart: 207, pageEnd: 224, percentComplete: 68, completed: false, createdAt: subDays(now, 3), updatedAt: subDays(now, 1) },
  { id: 'ch-14', bookId: '1', number: 14, title: 'How to Make Good Habits Inevitable and Bad Habits Impossible', pageStart: 225, pageEnd: 242, percentComplete: 0, completed: false, createdAt: subDays(now, 2), updatedAt: subDays(now, 2) },
  { id: 'ch-15', bookId: '1', number: 15, title: 'The Cardinal Rule of Behavior Change', pageStart: 243, pageEnd: 260, percentComplete: 0, completed: false, createdAt: subDays(now, 1), updatedAt: subDays(now, 1) },
  { id: 'ch-16', bookId: '1', number: 16, title: 'How to Stay Motivated in Life and Work', pageStart: 261, pageEnd: 278, percentComplete: 0, completed: false, createdAt: now, updatedAt: now },
  { id: 'ch-17', bookId: '1', number: 17, title: 'The Truth About Talent', pageStart: 279, pageEnd: 296, percentComplete: 0, completed: false, createdAt: now, updatedAt: now },
  { id: 'ch-18', bookId: '1', number: 18, title: 'The Goldilocks Rule: How to Stay Focused on Your Goals', pageStart: 297, pageEnd: 320, percentComplete: 0, completed: false, createdAt: now, updatedAt: now },
];

export const mockNotes: Note[] = [
  {
    id: 'note-1',
    libraryEntryId: 'entry-1',
    type: 'note',
    text: 'The 2-minute rule: When you start a new habit, it should take less than two minutes to do. The idea is to make your habits as easy as possible to start.',
    page: 210,
    chapter: 13,
    tags: ['habits', 'productivity', '2-minute-rule'],
    isFavorite: true,
    createdAt: subDays(now, 1),
    updatedAt: subDays(now, 1),
  },
  {
    id: 'note-2',
    libraryEntryId: 'entry-1',
    type: 'quote',
    text: 'You do not rise to the level of your goals. You fall to the level of your systems.',
    page: 27,
    chapter: 3,
    tags: ['systems', 'goals', 'favorite'],
    isFavorite: true,
    createdAt: subDays(now, 12),
    updatedAt: subDays(now, 12),
  },
  {
    id: 'note-3',
    libraryEntryId: 'entry-1',
    type: 'highlight',
    text: 'Habits are the compound interest of self-improvement. The same way that money multiplies through compound interest, the effects of your habits multiply as you repeat them.',
    page: 15,
    chapter: 1,
    tags: ['compound-interest', 'self-improvement'],
    isFavorite: false,
    createdAt: subDays(now, 14),
    updatedAt: subDays(now, 14),
  },
  {
    id: 'note-4',
    libraryEntryId: 'entry-1',
    type: 'reflection',
    text: 'Reading this chapter made me realize how much I\'ve been focusing on outcomes rather than identity. I want to become a reader, not just read 20 books. I want to become a writer, not just write a book. This shift in perspective changes everything.',
    page: 30,
    chapter: 3,
    tags: ['identity', 'reflection', 'mindset'],
    isFavorite: true,
    createdAt: subDays(now, 13),
    updatedAt: subDays(now, 13),
  },
  {
    id: 'note-5',
    libraryEntryId: 'entry-2',
    type: 'quote',
    text: 'We are the games we play. And the games we play are the stories we tell.',
    page: 156,
    chapter: 8,
    tags: ['games', 'stories', 'identity'],
    isFavorite: true,
    createdAt: subDays(now, 90),
    updatedAt: subDays(now, 90),
  },
  {
    id: 'note-6',
    libraryEntryId: 'entry-2',
    type: 'note',
    text: 'The way Zevin writes about creative partnership - it\'s not just collaboration, it\'s a form of love. The vulnerability required to make something together.',
    page: 200,
    chapter: 10,
    tags: ['creativity', 'partnership', 'vulnerability'],
    isFavorite: false,
    createdAt: subDays(now, 88),
    updatedAt: subDays(now, 88),
  },
  {
    id: 'note-7',
    libraryEntryId: 'entry-3',
    type: 'quote',
    text: 'The best way to help someone is not to give them advice but to ask them questions.',
    page: 89,
    chapter: 5,
    tags: ['creativity', 'coaching', 'questions'],
    isFavorite: true,
    createdAt: subDays(now, 70),
    updatedAt: subDays(now, 70),
  },
];

export const mockShelves: Shelf[] = [
  { id: 'shelf-1', name: 'All Books', description: 'Your complete library', bookIds: ['1', '2', '3', '4', '5', '6', '7', '8'], isDefault: true, color: '#f59e0b', icon: 'book-open', createdAt: subDays(now, 200), updatedAt: subDays(now, 1) },
  { id: 'shelf-2', name: 'Favorites', description: 'Books you\'ve loved', bookIds: ['1', '2', '4', '8'], isDefault: true, color: '#f59e0b', icon: 'heart', createdAt: subDays(now, 180), updatedAt: subDays(now, 10) },
  { id: 'shelf-3', name: 'Currently Reading', description: 'Books in progress', bookIds: ['1'], isDefault: true, color: '#f59e0b', icon: 'book-open', createdAt: subDays(now, 180), updatedAt: subDays(now, 1) },
  { id: 'shelf-4', name: 'Creative Practice', description: 'Books on creativity and art', bookIds: ['3'], isDefault: false, color: '#c2410c', icon: 'palette', createdAt: subDays(now, 90), updatedAt: subDays(now, 65) },
  { id: 'shelf-5', name: 'Sci-Fi & Fantasy', description: 'Other worlds and futures', bookIds: ['5'], isDefault: false, color: '#15803d', icon: 'rocket', createdAt: subDays(now, 45), updatedAt: subDays(now, 30) },
  { id: 'shelf-6', name: 'Nature & Wisdom', description: 'Indigenous knowledge and nature', bookIds: ['6'], isDefault: false, color: '#7c3aed', icon: 'leaf', createdAt: subDays(now, 30), updatedAt: subDays(now, 30) },
];

export const mockAuthors: Author[] = [
  { id: 'author-1', name: 'James Clear', avatarUrl: 'https://images.unsplash.com/photo-1649710025212-5b63cda94759?q=80&w=1470&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D', bio: 'James Clear is an author and speaker focused on habits, decision making, and continuous improvement.', birthYear: 1986, bookCount: 1, createdAt: subDays(now, 200), updatedAt: subDays(now, 10) },
  { id: 'author-2', name: 'Gabrielle Zevin', avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop&crop=face', bio: 'Gabrielle Zevin is an American author and screenwriter.', birthYear: 1977, bookCount: 1, createdAt: subDays(now, 150), updatedAt: subDays(now, 5) },
  { id: 'author-3', name: 'Rick Rubin', avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop&crop=face', bio: 'Rick Rubin is an American record producer.', birthYear: 1963, bookCount: 1, createdAt: subDays(now, 100), updatedAt: subDays(now, 2) },
  { id: 'author-4', name: 'Matt Haig', avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&h=100&fit=crop&crop=face', bio: 'Matt Haig is an English author and journalist.', birthYear: 1975, bookCount: 1, createdAt: subDays(now, 80), updatedAt: subDays(now, 1) },
  { id: 'author-5', name: 'Andy Weir', avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=100&h=100&fit=crop&crop=face', bio: 'Andy Weir is an American novelist.', birthYear: 1972, bookCount: 1, createdAt: subDays(now, 60), updatedAt: subDays(now, 3) },
  { id: 'author-6', name: 'Robin Wall Kimmerer', avatarUrl: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop&crop=face', bio: 'Robin Wall Kimmerer is a scientist and author.', birthYear: 1953, bookCount: 1, createdAt: subDays(now, 40), updatedAt: subDays(now, 7) },
];

export const mockTags: Tag[] = [
  { id: 'tag-1', name: 'habits', usageCount: 3, color: '#f59e0b', createdAt: subDays(now, 14) },
  { id: 'tag-2', name: 'productivity', usageCount: 2, color: '#60a5fa', createdAt: subDays(now, 14) },
  { id: 'tag-3', name: 'self-improvement', usageCount: 2, color: '#34d399', createdAt: subDays(now, 14) },
  { id: 'tag-4', name: 'identity', usageCount: 2, color: '#a78bfa', createdAt: subDays(now, 13) },
  { id: 'tag-5', name: 'creativity', usageCount: 2, color: '#c084fc', createdAt: subDays(now, 90) },
];

export const mockReadingGoal: ReadingGoal = {
  id: 'goal-2026',
  year: 2026,
  targetBooks: 24,
  targetPages: 10000,
  targetMinutes: 15000,
  createdAt: startOfYear(now),
  updatedAt: now,
};

export const mockStats: ReadingStats = {
  booksRead: 18,
  pagesRead: 6842,
  readingTimeMinutes: 8420,
  averageRating: 4.6,
  longestStreak: 28,
  currentStreak: 12,
  booksThisYear: 18,
  pagesThisYear: 6842,
  averagePagesPerDay: 32,
  averagePagesPerHour: 48,
  averageBooksPerMonth: 2.2,
  longestBook: { title: 'Project Hail Mary', pages: 496 },
  shortestBook: { title: 'The Psychology of Money', pages: 256 },
  mostProductiveMonth: { month: 'June', books: 4, pages: 1420 },
  genreDistribution: [
    { genre: 'Self-Improvement', count: 6, pages: 1920, percent: 34 },
    { genre: 'Fiction', count: 5, pages: 1850, percent: 28 },
    { genre: 'Biography & Memoir', count: 4, pages: 1400, percent: 20 },
    { genre: 'Psychology & Science', count: 3, pages: 1672, percent: 18 },
  ],
  formatDistribution: [
    { format: 'Paperback', count: 8, percent: 44 },
    { format: 'Hardcover', count: 5, percent: 28 },
    { format: 'Kindle / E-book', count: 3, percent: 17 },
    { format: 'Audiobook', count: 2, percent: 11 },
  ],
  ratingDistribution: [
    { rating: 5, count: 9 },
    { rating: 4.5, count: 5 },
    { rating: 4, count: 3 },
    { rating: 3.5, count: 1 },
    { rating: 3, count: 0 },
  ],
  monthlyPages: [
    { month: 'Jan', pages: 420, books: 1 },
    { month: 'Feb', pages: 580, books: 2 },
    { month: 'Mar', pages: 360, books: 1 },
    { month: 'Apr', pages: 760, books: 2 },
    { month: 'May', pages: 620, books: 2 },
    { month: 'Jun', pages: 880, books: 3 },
    { month: 'Jul', pages: 690, books: 2 },
    { month: 'Aug', pages: 920, books: 3 },
    { month: 'Sep', pages: 740, books: 2 },
    { month: 'Oct', pages: 810, books: 2 },
    { month: 'Nov', pages: 540, books: 1 },
    { month: 'Dec', pages: 670, books: 2 },
  ],
  monthlyBooks: [
    { month: 'Jan', count: 1 }, { month: 'Feb', count: 2 }, { month: 'Mar', count: 1 },
    { month: 'Apr', count: 2 }, { month: 'May', count: 2 }, { month: 'Jun', count: 3 },
    { month: 'Jul', count: 2 }, { month: 'Aug', count: 3 }, { month: 'Sep', count: 2 },
    { month: 'Oct', count: 2 }, { month: 'Nov', count: 1 }, { month: 'Dec', count: 2 },
  ],
  heatmapData: Array.from({ length: 90 }, (_, i) => ({
    date: format(subDays(now, 89 - i), 'yyyy-MM-dd'),
    minutes: Math.random() > 0.25 ? Math.floor(Math.random() * 60) + 15 : 0,
  })),
  topAuthors: [
    { author: mockAuthors[0], booksRead: 1, pagesRead: 320 },
    { author: mockAuthors[1], booksRead: 1, pagesRead: 416 },
    { author: mockAuthors[2], booksRead: 1, pagesRead: 432 },
    { author: mockAuthors[3], booksRead: 1, pagesRead: 304 },
    { author: mockAuthors[4], booksRead: 1, pagesRead: 496 },
  ],
};
